language: node_js
node_js:
- lts/*
cache: yarn
script: yarn deploy
after_script: yarn alias
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  # NOW_TOKEN
  - secure: Jmcr3T0DW4mrads0gyy8yHCEzz25z3IZiJ12smCC0P6xVE6XcxD90JUwAzpjnNl9cQn/JyMKy+hdI2CyhNQ7tw4rt0zE5dNhrMdpHhY6XOwvOsSF9CyFjITz/W5/Z0C4XNHJ057dnSLAaV4tFFLDHZb9+Tq2yhm1uc7vdVXOzVsd6wNZnJ8HCUlpkWSe1HoetyDa+CpqiP8vMNa4LjSZuVO4iiQ5TT8bUof/YzXtx+QBY/ppDywuxwF1nzEp03LeiB0RVyCLaOPRLruSpzHUeluTx0TKl+GnTzqTOI1Fh2THwo98aJ2VZrL0Kst7KNCjnv0LkrC3RsGLvGmqevw4MFe/A1+KTYLfWfj2N4w5A/ZUVcIGcO72JXKie5HC0vBRD2Mk0zTZhdkfrdaxDvKehTYMH4DIksKtHFGCYm7XXZbcsUxgZyMIp4gJtitCGlSXX7WmMzjjlHAa4RIY1VxIwT0MjrnlY+wVLu+lP9Vr+klU5j0hTkBiKRYirQMntEV048Yv2QICQ1adZ4OIUjIn3SakHQ+MGD7IxWxjtwOYhF6ojZPSkDBSb90Oqa84npdvInLf3wMYz1i6Xb6p+MC/1IYP7pZVu/xcEzCw45/ZtyEWbB6Te/ZsWj1f9ks/AbjgfSSqzpTUaqnQ8ietPEEho2ot5/XLoTOL3yF+bCfDNW0=
