language: node_js
node_js:
- lts/*
cache: yarn
script: yarn deploy
after_script: yarn alias
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    # NOW_TOKEN
    - secure: lg9hWHw8UR9BQDKgP0asVDqcNX1nXw2MeU7cUTx6B23VBZLZ1QZZ5MNmNOP97l0WvYADEk+bhsciboeCKMBkI1dNnqu8tIf5EBQoOdFTfqKJGINiVlx9b0jF79HSeBDQWppLE5ckroRj3Zcn1qaWAAgCQahYyBXuUFajWQXatiRZS7KVqUAMcF9XPnQotORG/M3ltyQv9WfFjp3sCc8LSPbat8rpCBEStuzk/u8Zl23VVRGkbQKPdKuwDDOuBuv7hvM70Ul46lDKwMAENZu90pny5ocNrrEqHos5a+M3Jm4GEIu6cru2n5yvvi6UHEke1kyon/1FOorah9MJy9FD81CiqIjes7Vwslw7lOgfDpPIU2jLZiX/uX99dXT+wEeY1BCx29kLVSdkugLCYG0iycgrhHF65ABpGWQP5NrR6lGXzf0UqJZSVNIYXMs7QajrLqS0ALQFxiwxY0cn9rnn/BSN99GM5gxe5YC0vS9KlNlZz5r01iTerf7iw/jA1N6KALI1brTsAJVTma4JrxWjUZSNOSAcN8LKSZ88PUG7Xtaezbda8diuxhUJ5KTpSNKoN89/Y1TJRrN5uD6TMiwvAUfqLzhZaqpGvrYDhc0t9jeM6q53te9PvogtlcK2RfPIn1YxPvBQo7amUveXyep/TNdMkm92WjQ/Mg2l9maOHsY=
