// check https://perishablepress.com/6g/
// check https://perishablepress.com/block-bad-bots/
// check https://www.winhelp.info/stop-fake-user-agents-with-htaccess.html
// check https://github.com/atomantic/is-ua-bot/blob/master/data/bots.js
// from http://johannburkard.de/blog/www/spam/The-top-10-spam-bot-user-agents-you-MUST-block-NOW.html
// "". That’s right. An empty user agent. If someone can’t be arsed to set a user-agent, why should you serve him anything?
// ^Java. Not necessarily anything containing Java but user agents starting with Java.
// ^Jakarta. Don’t ask. Just block.
// User-Agent. User agents containing User-Agent are most likely spambots operating from Layered Technologies’s network – which you should block as well.
// compatible ;. Note the extra space. Email harvester.
// "Mozilla". Only the string Mozilla of course.
// libwww, lwp-trivial, curl, PHP/, urllib, GT::WWW, Snoopy, MFC_Tear_Sample, HTTP::Lite, PHPCrawl, URI::Fetch, Zend_Http_Client, http client, PECL::HTTP. These are all HTTP libraries I DO NOT WANT.
// panscient.com. Who would forget panscient.com in a list of bad bots?
// IBM EVV, Bork-edition, Fetch API Request.
// [A-Z][a-z]{3,} [a-z]{4,} [a-z]{4,}. This matches nonsense user-agents such as Zobv zkjgws pzjngq. Most of these originate from layeredtech.com. Did I mention you should block Layered Technologies?
// WEP Search, Wells Search II, Missigua Locator, ISC Systems iRc Search 2.1, Microsoft URL Control, Indy Library. Oldies but goldies. Sort of.

// https://perishablepress.com/4g-ultimate-user-agent-blacklist/
export default {
  '^$': true,
  '<': true,
  '>': true,
  "'": true,
  '%': true,
  _iRc: true,
  _Works: true,
  // '@\$x': true,
  // '<\?': true,
  // '\$x0e': true,
  // '\+select\+': true,
  // '\+union\+': true,
  // '1,\\1,1,': true,
  // '2icommerce': true,
  // '3GSE': true,
  // '4all': true,
  // '59\.64\.153\.': true,
  // '88\.0\.106\.': true,
  // '98': true,
  // '85\.17\.': true,
  // 'A_Browser': true,
  // 'ABAC': true,
  // 'Abont': true,
  // 'abot': true,
  // 'Accept': true,
  // 'Access': true,
  // 'Accoo': true,
  // 'AceFTP': true,
  // 'Acme': true,
  // 'ActiveTouristBot': true,
  // 'Address': true,
  // 'Adopt': true,
  // 'adress': true,
  // 'adressendeutschland': true,
  // 'ADSARobot': true,
  // 'agent': true,
  // 'ah-ha': true,
  // 'Ahead': true,
  // 'AESOP_com_SpiderMan': true,
  // 'aipbot': true,
  // 'Alarm': true,
  // 'Albert': true,
  // 'Alek': true,
  // 'Alexibot': true,
  // 'Alligator': true,
  // 'AllSubmitter': true,
  // 'alma': true,
  // 'almaden': true,
  // 'ALot': true,
  // 'Alpha': true,
  // 'aktuelles': true,
  // 'Akregat': true,
  // 'Amfi': true,
  // 'amzn_assoc': true,
  // 'Anal': true,
  // 'Anarchie': true,
  // 'andit': true,
  // 'Anon': true,
  // 'AnotherBot': true,
  // 'Ansearch': true,
  // 'AnswerBus': true,
  // 'antivirx': true,
  // 'Apexoo': true,
  // 'appie': true,
  // 'Aqua_Products': true,
  // 'Arachmo': true,
  // 'archive': true,
  // 'arian': true,
  // 'ASPSe': true,
  // 'ASSORT': true,
  // 'aster': true,
  // 'Atari': true,
  // 'ATHENS': true,
  // 'AtHome': true,
  // 'Atlocal': true,
  // 'Atomic_Email_Hunter': true,
  // 'Atomz': true,
  // 'Atrop': true,
  // '^attach': true,
  // 'attrib': true,
  // 'autoemailspider': true,
  // 'autohttp': true,
  // 'axod': true,
  // 'batch': true,
  // 'b2w': true,
  // 'Back': true,
  // 'BackDoorBot': true,
  // 'BackStreet': true,
  // 'BackWeb': true,
  // 'Badass': true,
  // 'Baid': true,
  // 'Bali': true,
  // 'Bandit': true,
  // 'Baidu': true,
  // 'Barry': true,
  // 'BasicHTTP': true,
  // 'BatchFTP': true,
  // 'bdfetch': true,
  // 'beat': true,
  // 'Become': true,
  // 'Beij': true,
  // 'BenchMark': true,
  // 'berts': true,
  // 'bew': true,
  // 'big.brother': true,
  // 'Bigfoot': true,
  // 'Bilgi': true,
  // 'Bison': true,
  // 'Bitacle': true,
  // 'Biz360': true,
  // 'Black': true,
  // 'Black.Hole': true,
  // 'BlackWidow': true,
  // 'bladder.fusion': true,
  // 'Blaiz': true,
  // 'Blog.Checker': true,
  // 'Blogl': true,
  // 'BlogPeople': true,
  // 'Blogshares.Spiders': true,
  // 'Bloodhound': true,
  // 'Blow': true,
  // 'bmclient': true,
  // 'Board': true,
  // 'BOI': true,
  // 'boitho': true,
  // 'Bond': true,
  // 'Bookmark.search.tool': true,
  // 'boris': true,
  // 'Bost': true,
  // 'Boston.Project': true,
  // 'BotRightHere': true,
  // 'Bot.mailto:craftbot@yahoo.com': true,
  // 'BotALot': true,
  // 'botpaidtoclick': true,
  // 'botw': true,
  // 'brandwatch': true,
  // 'BravoBrian': true,
  // 'Brok': true,
  // 'Bropwers': true,
  // 'Broth': true,
  // 'browseabit': true,
  // 'BrowseX': true,
  // 'Browsezilla': true,
  // 'Bruin': true,
  // 'bsalsa': true,
  // 'Buddy': true,
  // 'Build': true,
  // 'Built': true,
  // 'Bulls': true,
  // 'bumblebee': true,
  // 'Bunny': true,
  // 'Busca': true,
  // 'Busi': true,
  // 'Buy': true,
  // 'bwh3': true,
  // 'c-spider': true,
  // 'CafeK': true,
  // 'Cafi': true,
  // 'camel': true,
  // 'Cand': true,
  // 'captu': true,
  // 'Catch': true,
  // 'cd34': true,
  // 'Ceg': true,
  // 'CFNetwork': true,
  // 'cgichk': true,
  // 'Cha0s': true,
  // 'Chang': true,
  // 'chaos': true,
  // 'Char': true,
  // 'char\(32,35\)': true,
  // 'charlotte': true,
  // 'CheeseBot': true,
  // 'Chek': true,
  // 'CherryPicker': true,
  // 'chill': true,
  // 'ChinaClaw': true,
  // 'CICC': true,
  // 'Cisco': true,
  // 'Cita': true,
  // 'Clam': true,
  // 'Claw': true,
  // 'Click.Bot': true,
  // 'clipping': true,
  // 'clshttp': true,
  // 'Clush': true,
  // 'COAST': true,
  // 'ColdFusion': true,
  // 'Coll': true,
  // 'Comb': true,
  // 'commentreader': true,
  // 'Compan': true,
  // 'contact': true,
  // 'Control': true,
  // 'contype': true,
  // 'Conc': true,
  // 'Conv': true,
  // 'Copernic': true,
  // 'Copi': true,
  // 'Copy': true,
  // 'Coral': true,
  // 'Corn': true,
  // 'core-project': true,
  // 'cosmos': true,
  // 'costa': true,
  // 'cr4nk': true,
  // 'crank': true,
  // 'craft': true,
  // 'Crap': true,
  // 'Crawler0': true,
  // 'Crazy': true,
  // 'Cres': true,
  // 'cs-CZ': true,
  // 'cuill': true,
  // 'Curl': true,
  // 'Custo': true,
  // 'Cute': true,
  // 'CSHttp': true,
  // 'Cyber': true,
  // 'cyberalert': true,
  // '^DA$': true,
  // 'daoBot': true,
  // 'DARK': true,
  // 'Data': true,
  // 'Daten': true,
  // 'Daum': true,
  // 'dcbot': true,
  // 'dcs': true,
  // 'Deep': true,
  // 'DepS': true,
  // 'Detect': true,
  // 'Deweb': true,
  // 'Diam': true,
  // 'Digger': true,
  // 'Digimarc': true,
  // 'digout4uagent': true,
  // 'DIIbot': true,
  // 'Dillo': true,
  // 'Ding': true,
  // 'DISC': true,
  // 'discobot': true,
  // 'Disp': true,
  // 'Ditto': true,
  // 'DLC': true,
  // 'DnloadMage': true,
  // 'DotBot': true,
  // 'Doubanbot': true,
  // 'Download': true,
  // 'Download.Demon': true,
  // 'Download.Devil': true,
  // 'Download.Wonder': true,
  // 'Downloader': true,
  // 'drag': true,
  // 'DreamPassport': true,
  // 'Drec': true,
  // 'Drip': true,
  // 'dsdl': true,
  // 'dsok': true,
  // 'DSurf': true,
  // 'DTAAgent': true,
  // 'DTS': true,
  // 'Dual': true,
  // 'dumb': true,
  // 'DynaWeb': true,
  // 'e-collector': true,
  // 'eag': true,
  // 'earn': true,
  // 'EARTHCOM': true,
  // 'EasyDL': true,
  // 'ebin': true,
  // 'EBM-APPLE': true,
  // 'EBrowse': true,
  // 'eCatch': true,
  // 'echo': true,
  // 'ecollector': true,
  // 'Edco': true,
  // 'edgeio': true,
  // 'efp@gmx\.net': true,
  // 'EirGrabber': true,
  // 'email': true,
  // 'Email.Extractor': true,
  // 'EmailCollector': true,
  // 'EmailSearch': true,
  // 'EmailSiphon': true,
  // 'EmailWolf': true,
  // 'Emer': true,
  // 'empas': true,
  // 'Enfi': true,
  // 'Enhan': true,
  // 'Enterprise_Search': true,
  // 'envolk': true,
  // 'erck': true,
  // 'EroCr': true,
  // 'ESurf': true,
  // 'Eval': true,
  // 'Evil': true,
  // 'Evere': true,
  // 'EWH': true,
  // 'Exabot': true,
  // 'Exact': true,
  // 'EXPLOITER': true,
  // 'Expre': true,
  // 'Extra': true,
  // 'ExtractorPro': true,
  // 'EyeN': true,
  // 'FairAd': true,
  // 'Fake': true,
  // 'FANG': true,
  // 'FAST': true,
  // 'fastlwspider': true,
  // 'FavOrg': true,
  // 'Favorites.Sweeper': true,
  // 'Faxo': true,
  // 'FDM_1': true,
  // 'FDSE': true,
  // 'fetch': true,
  // 'FEZhead': true,
  // 'Filan': true,
  // 'FileHound': true,
  // 'find': true,
  // 'Firebat': true,
  // 'Firefox.2\.0': true,
  // 'Firs': true,
  // 'Flam': true,
  // 'Flash': true,
  // 'FlickBot': true,
  // 'Flip': true,
  // 'fluffy': true,
  // 'flunky': true,
  // 'focus': true,
  // 'Foob': true,
  // 'Fooky': true,
  // 'Forex': true,
  // 'Forum': true,
  // 'ForV': true,
  // 'Fost': true,
  // 'Foto': true,
  // 'Foun': true,
  // 'Franklin.Locator': true,
  // 'freefind': true,
  // 'FreshDownload': true,
  // 'FrontPage': true,
  // 'FSurf': true,
  // 'Fuck': true,
  // 'Fuer': true,
  // 'futile': true,
  // 'Fyber': true,
  // 'Gais': true,
  // 'GalaxyBot': true,
  // 'Galbot': true,
  // 'Gamespy_Arcade': true,
  // 'GbPl': true,
  // 'Gener': true,
  // 'geni': true,
  // 'Geona': true,
  // 'Get': true,
  // 'gigabaz': true,
  // 'Gira': true,
  // 'Ginxbot': true,
  // 'gluc': true,
  // 'glx.?v': true,
  // 'gnome': true,
  // 'Go.Zilla': true,
  // 'Goldfire': true,
  // 'Google.Wireless.Transcoder': true,
  // 'Googlebot-Image': true,
  // 'Got-It': true,
  // 'GOFORIT': true,
  // 'gonzo': true,
  // 'GornKer': true,
  // 'GoSearch': true,
  // '^gotit$': true,
  // 'gozilla': true,
  // 'grab': true,
  // 'Grabber': true,
  // 'GrabNet': true,
  // 'Grub': true,
  // 'Grup': true,
  // 'Graf': true,
  // 'Green.Research': true,
  // 'grub': true,
  // 'grub-client': true,
  // 'gsa-cra': true,
  // 'GSearch': true,
  // 'GT::WWW': true,
  // 'GuideBot': true,
  // 'guruji': true,
  // 'gvfs': true,
  // 'Gyps': true,
  // 'hack': true,
  // 'haha': true,
  // 'hailo': true,
  // 'Harv': true,
  // 'Hatena': true,
  // 'Hax': true,
  // 'Head': true,
  // 'Helm': true,
  // 'herit': true,
  // 'hgre': true,
  // 'hhjhj@yahoo': true,
  // 'Hippo': true,
  // 'hloader': true,
  // 'HMView': true,
  // 'holm': true,
  // 'holy': true,
  // 'HomePageSearch': true,
  // 'HooWWWer': true,
  // 'HouxouCrawler': true,
  // 'HMSE': true,
  // 'HPPrint': true,
  // 'htdig': true,
  // 'HTTPConnect': true,
  // 'httpdown': true,
  // 'http.generic': true,
  // 'HTTPGet': true,
  // 'httplib': true,
  // 'HTTPRetriever': true,
  // 'HTTrack': true,
  // 'human': true,
  // 'Huron': true,
  // 'hverify': true,
  // 'Hybrid': true,
  // 'Hyper': true,
  // 'ia_archiver': true,
  // 'iaskspi': true,
  // 'IBM_Planetwide': true,
  // 'iCCra': true,
  // 'ichiro': true,
  // 'ID-Search': true,
  // 'IDA': true,
  // 'IDBot': true,
  // 'IEAuto': true,
  // 'IEMPT': true,
  // 'iexplore\.exe': true,
  // 'iGetter': true,
  // 'Ilse': true,
  // 'Iltrov': true,
  // 'Image': true,
  // 'Image.Stripper': true,
  // 'Image.Sucker': true,
  // 'imagefetch': true,
  // 'iimds_monitor': true,
  // 'Incutio': true,
  // 'IncyWincy': true,
  // 'Indexer': true,
  // 'Industry.Program': true,
  // 'Indy': true,
  // 'InetURL': true,
  // 'informant': true,
  // 'InfoNav': true,
  // 'InfoTekies': true,
  // 'Ingelin': true,
  // 'Innerpr': true,
  // 'Inspect': true,
  // 'InstallShield.DigitalWizard': true,
  // 'Insuran\.': true,
  // 'Intellig': true,
  // 'Intelliseek': true,
  // 'InterGET': true,
  // 'Internet.Ninja': true,
  // 'Internet.x': true,
  // 'Internet_Explorer': true,
  // 'InternetLinkagent': true,
  // 'InternetSeer.com': true,
  // 'Intraf': true,
  // 'IP2': true,
  // 'Ipsel': true,
  // 'Iria': true,
  // 'IRLbot': true,
  // 'Iron33': true,
  // 'Irvine': true,
  // 'ISC_Sys': true,
  // 'iSilo': true,
  // 'ISRCCrawler': true,
  // 'ISSpi': true,
  // 'IUPUI.Research.Bot': true,
  // 'Jady': true,
  // 'Jaka': true,
  // 'Jam': true,
  // '^Java': true,
  // 'java\/': true,
  // 'Java\(tm\)': true,
  // 'JBH.agent': true,
  // 'Jenny': true,
  // 'JetB': true,
  // 'JetC': true,
  // 'jeteye': true,
  // 'jiro': true,
  // 'JoBo': true,
  // 'JOC': true,
  // 'jupit': true,
  // 'Just': true,
  // 'Jyx': true,
  // 'Kapere': true,
  // 'kash': true,
  // 'Kazo': true,
  // 'KBee': true,
  // 'Kenjin': true,
  // 'Kernel': true,
  // 'Keywo': true,
  // 'KFSW': true,
  // 'KKma': true,
  // 'Know': true,
  // 'kosmix': true,
  // 'KRAE': true,
  // 'KRetrieve': true,
  // 'Krug': true,
  // 'ksibot': true,
  // 'ksoap': true,
  // 'Kum': true,
  // 'KWebGet': true,
  // 'Lachesis': true,
  // 'lanshan': true,
  // 'Lapo': true,
  // 'larbin': true,
  // 'leacher': true,
  // 'leech': true,
  // 'LeechFTP': true,
  // 'LeechGet': true,
  // 'leipzig\.de': true,
  // 'Lets': true,
  // 'Lexi': true,
  // 'lftp': true,
  // 'Libby': true,
  // 'libcrawl': true,
  // 'libcurl': true,
  // 'libfetch': true,
  // 'libghttp': true,
  // 'libWeb': true,
  // 'libwhisker': true,
  // 'libwww': true,
  // 'libwww-FM': true,
  // 'libwww-perl': true,
  // 'LightningDownload': true,
  // 'likse': true,
  // 'Linc': true,
  // 'Link': true,
  // 'Link.Sleuth': true,
  // 'LinkextractorPro': true,
  // 'Linkie': true,
  // 'LINKS.ARoMATIZED': true,
  // 'LinkScan': true,
  // 'linktiger': true,
  // 'LinkWalker': true,
  // 'Lint': true,
  // 'List': true,
  // 'lmcrawler': true,
  // 'LMQ': true,
  // 'LNSpiderguy': true,
  // 'loader': true,
  // 'LocalcomBot': true,
  // 'Locu': true,
  // 'London': true,
  // 'lone': true,
  // 'looksmart': true,
  // 'loop': true,
  // 'Lork': true,
  // 'LTH_': true,
  // 'lwp-request': true,
  // 'LWP': true,
  // 'lwp-trivial': true,
  // 'Mac.Finder': true,
  // 'Macintosh;.I;.PPC': true,
  // 'Mac_F': true,
  // 'magi': true,
  // 'Mag-Net': true,
  // 'Magnet': true,
  // 'Magp': true,
  // 'Mail.Sweeper': true,
  // 'main': true,
  // 'majest': true,
  // 'Mam': true,
  // 'Mana': true,
  // 'MarcoPolo': true,
  // 'mark.blonin': true,
  // 'MarkWatch': true,
  // 'MaSagool': true,
  // 'Mass': true,
  // 'Mass.Downloader': true,
  // 'Mata': true,
  // 'mavi': true,
  // 'McBot': true,
  // 'Mecha': true,
  // 'MCspider': true,
  // 'mediapartners': true,
  // '^Memo': true,
  // 'MEGAUPLOAD': true,
  // 'MetaProducts.Download.Express': true,
  // 'Metaspin': true,
  // 'Mete': true,
  // 'Microsoft.Data.Access': true,
  // 'Microsoft.URL': true,
  // 'Microsoft_Internet_Explorer': true,
  // 'MIDo': true,
  // 'MIIx': true,
  // 'miner': true,
  // 'Mira': true,
  // 'MIRE': true,
  // 'Mirror': true,
  // 'Miss': true,
  // 'Missauga': true,
  // 'Missigua.Locator': true,
  // 'Missouri.College.Browse': true,
  // 'Mist': true,
  // 'Mizz': true,
  // 'MJ12': true,
  // 'mkdb': true,
  // 'mlbot': true,
  // 'MLM': true,
  // 'MMMoCrawl': true,
  // 'MnoG': true,
  // 'moge': true,
  // 'Moje': true,
  // 'Monster': true,
  // 'Monza.Browser': true,
  // 'Mooz': true,
  // 'Moreoverbot': true,
  // 'MOT-MPx220': true,
  // 'mothra\/netscan': true,
  // 'mouse': true,
  // 'MovableType': true,
  // 'Mozdex': true,
  // 'Mozi!': true,
  // '^Mozilla$': true,
  // 'Mozilla\/1\.22': true,
  // 'Mozilla\/22': true,
  // '^Mozilla\/3\.0.\(compatible': true,
  // 'Mozilla\/3\.Mozilla\/2\.01': true,
  // 'Mozilla\/4\.0\(compatible': true,
  // 'Mozilla\/4\.08': true,
  // 'Mozilla\/4\.61.\(Macintosh': true,
  // 'Mozilla\/5\.0': true,
  // 'Mozilla\/7\.0': true,
  // 'Mozilla\/8': true,
  // 'Mozilla\/9': true,
  // 'Mozilla:': true,
  // 'Mozilla\/Firefox': true,
  // '^Mozilla.*Indy': true,
  // '^Mozilla.*NEWT': true,
  // '^Mozilla*MSIECrawler': true,
  // 'Mp3Bot': true,
  // 'MPF': true,
  // 'MRA': true,
  // 'MS.FrontPage': true,
  // 'MS.?Search': true,
  // 'MSFrontPage': true,
  // 'MSIE_6\.0': true,
  // 'MSIE6': true,
  // 'MSIECrawler': true,
  // 'msnbot-media': true,
  // 'msnbot-Products': true,
  // 'MSNPTC': true,
  // 'MSProxy': true,
  // 'MSRBOT': true,
  // 'multithreaddb': true,
  // 'musc': true,
  // 'MVAC': true,
  // 'MWM': true,
  // 'My_age': true,
  // 'MyApp': true,
  // 'MyDog': true,
  // 'MyEng': true,
  // 'MyFamilyBot': true,
  // 'MyGetRight': true,
  // 'MyIE2': true,
  // 'mysearch': true,
  // 'myurl': true,
  // 'NAG': true,
  // 'NAMEPROTECT': true,
  // 'NASA.Search': true,
  // 'nationaldirectory': true,
  // 'Naver': true,
  // 'Navr': true,
  // 'Near': true,
  // 'NetAnts': true,
  // 'netattache': true,
  // 'Netcach': true,
  // 'NetCarta': true,
  // 'Netcraft': true,
  // 'NetCrawl': true,
  // 'NetMech': true,
  // 'netprospector': true,
  // 'NetResearchServer': true,
  // 'NetSp': true,
  // 'Net.Vampire': true,
  // 'netX': true,
  // 'NetZ': true,
  // 'Neut': true,
  // 'newLISP': true,
  // 'NewsGatorInbox': true,
  // 'NEWT': true,
  // 'NEWT.ActiveX': true,
  // 'Next': true,
  // '^NG': true,
  // 'NICE': true,
  // 'nikto': true,
  // 'Nimb': true,
  // 'Ninja': true,
  // 'Ninte': true,
  // 'NIPGCrawler': true,
  // 'Noga': true,
  // 'nogo': true,
  // 'Noko': true,
  // 'Nomad': true,
  // 'Norb': true,
  // 'noxtrumbot': true,
  // 'NPbot': true,
  // 'NuSe': true,
  // 'Nutch': true,
  // 'Nutex': true,
  // 'NWSp': true,
  // 'Obje': true,
  // 'Ocel': true,
  // 'Octo': true,
  // 'ODI3': true,
  // 'oegp': true,
  // 'Offline': true,
  // 'Offline.Explorer': true,
  // 'Offline.Navigator': true,
  // 'OK.Mozilla': true,
  // 'omg': true,
  // 'Omni': true,
  // 'Onfo': true,
  // 'onyx': true,
  // 'OpaL': true,
  // 'OpenBot': true,
  // 'Openf': true,
  // 'OpenTextSiteCrawler': true,
  // 'OpenU': true,
  // 'Orac': true,
  // 'OrangeBot': true,
  // 'Orbit': true,
  // 'Oreg': true,
  // 'osis': true,
  // 'Outf': true,
  // 'Owl': true,
  // 'P3P': true,
  // 'PackRat': true,
  // 'PageGrabber': true,
  // 'PagmIEDownload': true,
  // 'pansci': true,
  // 'Papa': true,
  // 'Pars': true,
  // 'Patw': true,
  // 'pavu': true,
  // 'Pb2Pb': true,
  // 'pcBrow': true,
  // 'PEAR': true,
  // 'PEER': true,
  // 'PECL': true,
  // 'pepe': true,
  // 'Perl': true,
  // 'PerMan': true,
  // 'PersonaPilot': true,
  // 'Persuader': true,
  // 'petit': true,
  // 'PHP': true,
  // 'PHP.vers': true,
  // 'PHPot': true,
  // 'Phras': true,
  // 'PicaLo': true,
  // 'Piff': true,
  // 'Pige': true,
  // 'pigs': true,
  // '^Ping': true,
  // 'Pingd': true,
  // 'PingALink': true,
  // 'Pipe': true,
  // 'Plag': true,
  // 'Plant': true,
  // 'playstarmusic': true,
  // 'Pluck': true,
  // 'Pockey': true,
  // 'POE-Com': true,
  // 'Poirot': true,
  // 'Pomp': true,
  // 'Port.Huron': true,
  // 'Post': true,
  // 'powerset': true,
  // 'Preload': true,
  // 'press': true,
  // 'Privoxy': true,
  // 'Probe': true,
  // 'Program.Shareware': true,
  // 'Progressive.Download': true,
  // 'ProPowerBot': true,
  // 'prospector': true,
  // 'Provider.Protocol.Discover': true,
  // 'ProWebWalker': true,
  // 'Prowl': true,
  // 'Proxy': true,
  // 'Prozilla': true,
  // 'psbot': true,
  // 'PSurf': true,
  // 'psycheclone': true,
  // '^puf$': true,
  // 'Pulse': true,
  // 'Pump': true,
  // 'PushSite': true,
  // 'PussyCat': true,
  // 'PuxaRapido': true,
  // 'PycURL': true,
  // 'Pyth': true,
  // 'PyQ': true,
  // 'QuepasaCreep': true,
  // 'Query': true,
  // 'Quest': true,
  // 'QRVA': true,
  // 'Qweer': true,
  // 'radian': true,
  // 'Radiation': true,
  // 'Rambler': true,
  // 'RAMP': true,
  // 'RealDownload': true,
  // 'Reap': true,
  // 'Recorder': true,
  // 'RedCarpet': true,
  // 'RedKernel': true,
  // 'ReGet': true,
  // 'relevantnoise': true,
  // 'replacer': true,
  // 'Repo': true,
  // 'requ': true,
  // 'Rese': true,
  // 'Retrieve': true,
  // 'Rip': true,
  // 'Rix': true,
  // 'RMA': true,
  // 'Roboz': true,
  // 'Rogue': true,
  // 'Rover': true,
  // 'RPT-HTTP': true,
  // 'Rsync': true,
  // 'RTG30': true,
  // '.ru\)': true,
  // 'ruby': true,
  // 'Rufus': true,
  // 'Salt': true,
  // 'Sample': true,
  // 'SAPO': true,
  // 'Sauger': true,
  // 'savvy': true,
  // 'SBIder': true,
  // 'SBP': true,
  // 'SCAgent': true,
  // 'scan': true,
  // 'SCEJ_': true,
  // 'Sched': true,
  // 'Schizo': true,
  // 'Schlong': true,
  // 'Schmo': true,
  // 'Scout': true,
  // 'Scooter': true,
  // 'Scorp': true,
  // 'ScoutOut': true,
  // 'SCrawl': true,
  // 'screen': true,
  // 'script': true,
  // 'SearchExpress': true,
  // 'searchhippo': true,
  // 'Searchme': true,
  // 'searchpreview': true,
  // 'searchterms': true,
  // 'Second.Street.Research': true,
  // 'Security.Kol': true,
  // 'Seekbot': true,
  // 'Seeker': true,
  // 'Sega': true,
  // 'Sensis': true,
  // 'Sept': true,
  // 'Serious': true,
  // 'Sezn': true,
  // 'Shai': true,
  // 'Share': true,
  // 'Sharp': true,
  // 'Shaz': true,
  // 'shell': true,
  // 'shelo': true,
  // 'Sherl': true,
  // 'Shim': true,
  // 'Shiretoko': true,
  // 'ShopWiki': true,
  // 'SickleBot': true,
  // 'Simple': true,
  // 'Siph': true,
  // 'sitecheck': true,
  // 'SiteCrawler': true,
  // 'SiteSnagger': true,
  // 'Site.Sniper': true,
  // 'SiteSucker': true,
  // 'sitevigil': true,
  // 'SiteX': true,
  // 'Sleip': true,
  // 'Slide': true,
  // 'Slurpy.Verifier': true,
  // 'Sly': true,
  // 'Smag': true,
  // 'SmartDownload': true,
  // 'Smurf': true,
  // 'sna-': true,
  // 'snag': true,
  // 'Snake': true,
  // 'Snapbot': true,
  // 'Snip': true,
  // 'Snoop': true,
  // 'So-net': true,
  // 'SocSci': true,
  // 'sogou': true,
  // 'Sohu': true,
  // 'solr': true,
  // 'sootle': true,
  // 'Soso': true,
  // 'SpaceBison': true,
  // 'Spad': true,
  // 'Span': true,
  // 'spanner': true,
  // 'Speed': true,
  // 'Spegla': true,
  // 'Sphere': true,
  // 'Sphider': true,
  // 'spider': true,
  // 'SpiderBot': true,
  // 'SpiderEngine': true,
  // 'SpiderView': true,
  // 'Spin': true,
  // 'sproose': true,
  // 'Spurl': true,
  // 'Spyder': true,
  // 'Squi': true,
  // 'SQ.Webscanner': true,
  // 'sqwid': true,
  // 'Sqworm': true,
  // 'SSM_Ag': true,
  // 'Stack': true,
  // 'Stamina': true,
  // 'stamp': true,
  // 'Stanford': true,
  // 'Statbot': true,
  // 'State': true,
  // 'Steel': true,
  // 'Strateg': true,
  // 'Stress': true,
  // 'Strip': true,
  // 'studybot': true,
  // 'Style': true,
  // 'subot': true,
  // 'Suck': true,
  // 'Sume': true,
  // 'sun4m': true,
  // 'Sunrise': true,
  // 'SuperBot': true,
  // 'SuperBro': true,
  // 'Supervi': true,
  // 'Surf4Me': true,
  // 'SuperHTTP': true,
  // 'Surfbot': true,
  // 'SurfWalker': true,
  // 'Susi': true,
  // 'suza': true,
  // 'suzu': true,
  // 'Sweep': true,
  // 'sygol': true,
  // 'syncrisis': true,
  // 'Systems': true,
  // 'Szukacz': true,
  // 'Tagger': true,
  // 'Tagyu': true,
  // 'tAke': true,
  // 'Talkro': true,
  // 'TALWinHttpClient': true,
  // 'tamu': true,
  // 'Tandem': true,
  // 'Tarantula': true,
  // 'tarspider': true,
  // 'tBot': true,
  // 'TCF': true,
  // 'Tcs\/1': true,
  // 'TeamSoft': true,
  // 'Tecomi': true,
  // 'Teleport': true,
  // 'Telesoft': true,
  // 'Templeton': true,
  // 'Tencent': true,
  // 'Terrawiz': true,
  // 'Test': true,
  // 'TexNut': true,
  // 'trivial': true,
  // 'Turnitin': true,
  // 'The.Intraformant': true,
  // 'TheNomad': true,
  // 'Thomas': true,
  // 'TightTwatBot': true,
  // 'Timely': true,
  // 'Titan': true,
  // 'TMCrawler': true,
  // 'TMhtload': true,
  // 'toCrawl': true,
  // 'Todobr': true,
  // 'Tongco': true,
  // 'topic': true,
  // 'Torrent': true,
  // 'Track': true,
  // 'translate': true,
  // 'Traveler': true,
  // 'TREEVIEW': true,
  // 'True': true,
  // 'Tunnel': true,
  // 'turing': true,
  // 'Turnitin': true,
  // 'TutorGig': true,
  // 'TV33_Mercator': true,
  // 'Twat': true,
  // 'Tweak': true,
  // 'Twice': true,
  // 'Twisted.PageGetter': true,
  // 'Tygo': true,
  // 'ubee': true,
  // 'UCmore': true,
  // 'UdmSearch': true,
  // 'UIowaCrawler': true,
  // 'Ultraseek': true,
  // 'UMBC': true,
  // 'unf': true,
  // 'UniversalFeedParser': true,
  // 'unknown': true,
  // 'UPG1': true,
  // 'UtilMind': true,
  // 'URLBase': true,
  // 'URL.Control': true,
  // 'URL_Spider_Pro': true,
  // 'urldispatcher': true,
  // 'URLGetFile': true,
  // 'urllib': true,
  // 'URLSpiderPro': true,
  // 'URLy': true,
  // 'User-Agent': true,
  // 'UserAgent': true,
  // 'USyd': true,
  // 'Vacuum': true,
  // 'vagabo': true,
  // 'Valet': true,
  // 'Valid': true,
  // 'Vamp': true,
  // 'vayala': true,
  // 'VB_': true,
  // 'VCI': true,
  // 'VERI\~LI': true,
  // 'verif': true,
  // 'versus': true,
  // 'via': true,
  // 'Viewer': true,
  // 'virtual': true,
  // 'visibilitygap': true,
  // 'Visual': true,
  // 'vobsub': true,
  // 'Void': true,
  // 'VoilaBot': true,
  // 'voyager': true,
  // 'vspider': true,
  // 'VSyn': true,
  // 'w:PACBHO60': true,
  // 'w0000t': true,
  // 'W3C': true,
  // 'w3m': true,
  // 'w3search': true,
  // 'walhello': true,
  // 'Walker': true,
  // 'Wand': true,
  // 'WAOL': true,
  // 'WAPT': true,
  // 'Watch': true,
  // 'Wavefire': true,
  // 'wbdbot': true,
  // 'Weather': true,
  // 'web.by.mail': true,
  // 'Web.Data.Extractor': true,
  // 'Web.Downloader': true,
  // 'Web.Ima': true,
  // 'Web.Mole': true,
  // 'Web.Sucker': true,
  // 'Web2Mal': true,
  // 'Web2WAP': true,
  // 'WebaltBot': true,
  // 'WebAuto': true,
  // 'WebBandit': true,
  // 'Webbot': true,
  // 'WebCapture': true,
  // 'WebCat': true,
  // 'webcraft@bea': true,
  // 'Webclip': true,
  // 'webcollage': true,
  // 'WebCollector': true,
  // 'WebCopier': true,
  // 'WebCopy': true,
  // 'WebCor': true,
  // 'webcrawl': true,
  // 'WebDat': true,
  // 'WebDav': true,
  // 'webdevil': true,
  // 'webdownloader': true,
  // 'Webdup': true,
  // 'WebEMail': true,
  // 'WebEMailExtrac': true,
  // 'WebEnhancer': true,
  // 'WebFetch': true,
  // 'WebGo': true,
  // 'WebHook': true,
  // 'Webinator': true,
  // 'WebInd': true,
  // 'webitpr': true,
  // 'WebFilter': true,
  // 'WebFountain': true,
  // 'WebLea': true,
  // 'Webmaster': true,
  // 'WebmasterWorldForumBot': true,
  // 'WebMin': true,
  // 'WebMirror': true,
  // 'webmole': true,
  // 'webpic': true,
  // 'WebPin': true,
  // 'WebPix': true,
  // 'WebReaper': true,
  // 'WebRipper': true,
  // 'WebRobot': true,
  // 'WebSauger': true,
  // 'WebSite': true,
  // 'Website.eXtractor': true,
  // 'Website.Quester': true,
  // 'WebSnake': true,
  // 'webspider': true,
  // 'Webster': true,
  // 'WebStripper': true,
  // 'websucker': true,
  // 'WebTre': true,
  // 'WebVac': true,
  // 'webwalk': true,
  // 'WebWasher': true,
  // 'WebWeasel': true,
  // 'WebWhacker': true,
  // 'WebZIP': true,
  // 'Wells': true,
  // 'WEP_S': true,
  // 'WEP.Search.00': true,
  // 'WeRelateBot': true,
  // 'wget': true,
  // 'Whack': true,
  // 'Whacker': true,
  // 'whiz': true,
  // 'WhosTalking': true,
  // 'Widow': true,
  // 'Win67': true,
  // 'window.location': true,
  // 'Windows.95;': true,
  // 'Windows.95\)': true,
  // 'Windows.98;': true,
  // 'Windows.98\)': true,
  // 'Winodws': true,
  // 'Wildsoft.Surfer': true,
  // 'WinHT': true,
  // 'winhttp': true,
  // 'WinHttpRequest': true,
  // 'WinHTTrack': true,
  // 'Winnie.Poh': true,
  // 'wire': true,
  // 'WISEbot': true,
  // 'wisenutbot': true,
  // 'wish': true,
  // 'Wizz': true,
  // 'WordP': true,
  // 'Works': true,
  // 'world': true,
  // 'WUMPUS': true,
  // 'Wweb': true,
  // 'WWWC': true,
  // 'WWWOFFLE': true,
  // 'WWW-Collector': true,
  // 'WWW.Mechanize': true,
  // 'www.ranks.nl': true,
  // 'wwwster': true,
  // '^x$': true,
  // 'X12R1': true,
  // 'x-Tractor': true,
  // 'Xaldon': true,
  // 'Xenu': true,
  // 'XGET': true,
  // 'xirq': true,
  // 'Y!OASIS': true,
  // 'Y!Tunnel': true,
  // 'yacy': true,
  // 'YaDirectBot': true,
  // 'Yahoo-MMAudVid': true,
  // 'YahooSeeker': true,
  // 'YahooYSMcm': true,
  // 'Yamm': true,
  // 'Yand': true,
  // 'yang': true,
  // 'Yeti': true,
  // 'Yoono': true,
  // 'yori': true,
  // 'Yotta': true,
  // 'YTunnel': true,
  // 'Zade': true,
  // 'zagre': true,
  // 'ZBot': true,
  // 'Zeal': true,
  // 'ZeBot': true,
  // 'zerx': true,
  // 'Zeus': true,
  // 'ZIPCode': true,
  // 'Zixy': true,
  // 'zmao': true,
  // 'Zyborg': true,

  // added https://github.com/jeremyscalpello/express-nobots/blob/master/lib/bots.js
  '360Spider': true,
  'A6-Indexer': true,
  ADmantX: true,
  AISearchBot: true,
  Aboundex: true,
  AddThis: true,
  Adidxbot: true,
  AdvBot: true,
  Applebot: true,
  BUbiNG: true,
  'CC Metadata Scaper': true,
  'Commons-HttpClient': true,
  CrystalSemanticsBot: true,
  CyberPatrol: true,
  'Domain Re-Animator Bot': true,
  DuckDuckBot: true,
  'FAST Enterprise Crawler': true,
  'FAST-WebCrawler': true,
  Facebot: true,
  GingerCrawler: true,
  'Googlebot-Mobile': true,
  GrapeshotCrawler: true,
  IOI: true,
  InterfaxScanBot: true,
  'Linguee Bot': true,
  'Lipperhey SEO Service': true,
  Livelapbot: true,
  MJ12bot: true,
  'Mail.RU_Bot': true,
  'Mediapartners-Google': true,
  MegaIndex: true,
  'NerdByNature.Bot': true,
  'Python-urllib': true,
  Qwantify: true,
  RetrevoPageAnalyzer: true,
  SemanticScholarBot: true,
  SemrushBot: true,
  SimpleCrawler: true,
  TweetmemeBot: true,
  Twitterbot: true,
  Voyager: true,
  'WeSEE:Search': true,
  acoonbot: true,
  ahrefsbot: true,
  aihitbot: true,
  antibot: true,
  arabot: true,
  'archive.org_bot': true,
  backlinkcrawler: true,
  baiduspider: true,
  'bibnum.bnf': true,
  biglotron: true,
  bingbot: true,
  binlar: true,
  blekkobot: true,
  blexbot: true,
  'bnf.fr_bot': true,
  brainobot: true,
  buzzbot: true,
  cXensebot: true,
  careerbot: true,
  ccbot: true,
  changedetection: true,
  citeseerxbot: true,
  coccoc: true,
  'content crawler spider': true,
  convera: true,
  crawler4j: true,
  curl: true,
  domaincrawler: true,
  dotbot: true,
  drupact: true,
  ec2linkfinder: true,
  edisterbot: true,
  elisabot: true,
  'europarchive.org': true,
  exabot: true,
  ezooms: true,
  facebookexternalhit: true,
  findlink: true,
  findthatfile: true,
  findxbot: true,
  'fr-crawler': true,
  'g00g1e.net': true,
  gigablast: true,
  'gnam gnam spider': true,
  googlebot: true,
  'grub.org': true,
  gslfbot: true,
  heritrix: true,
  httpunit: true,
  httrack: true,
  integromedb: true,
  intelium_bot: true,
  'ip-web-crawler.com': true,
  'ips-agent': true,
  'it2media-domain-crawler': true,
  java: true,
  jyxobot: true,
  'lb-spider': true,
  linkdex: true,
  lipperhey: true,
  lssbot: true,
  lssrocketcrawler: true,
  ltx71: true,
  memorybot: true,
  msnbot: true,
  msrbot: true,
  nerdybot: true,
  netresearchserver: true,
  ngbot: true,
  'niki-bot': true,
  nutch: true,
  openindexspider: true,
  page2rss: true,
  panscient: true,
  phpcrawl: true,
  postrank: true,
  proximic: true,
  purebot: true,
  rogerbot: true,
  scribdbot: true,
  seekbot: true,
  'seokicks-robot': true,
  seznambot: true,
  'sistrix crawler': true,
  sitebot: true,
  'siteexplorer.info': true,
  slurp: true,
  smtbot: true,
  spbot: true,
  speedy: true,
  summify: true,
  tagoobot: true,
  teoma: true,
  toplistbot: true,
  turnitinbot: true,
  twengabot: true,
  urlappendbot: true,
  voilabot: true,
  wbsearchbot: true,
  'web-archive-net.com.bot': true,
  webcompanycrawler: true,
  webcrawler: true,
  'webmon ': true,
  wocbot: true,
  woriobot: true,
  wotbox: true,
  xovibot: true,
  'y!j-asr': true,
  yacybot: true,
  yandexbot: true,
  yanga: true,
  yeti: true,
  yoozBot: true,
  Slackbot: true,
  'Slack-ImgProxy': true,
  'Slackbot-LinkExpanding': true,
  Jorgee: true,
};
